import React, { useState, useCallback } from 'react';
import { View, Text, StyleSheet, FlatList, Platform, StatusBar, Share, TouchableOpacity, Alert } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useNavigation } from '@react-navigation/native';
import { useFocusEffect } from '@react-navigation/native';
import Animated, { FadeInUp } from 'react-native-reanimated';
import Icon from 'react-native-vector-icons/MaterialIcons';
import { Colors } from '../constants/Colors';
import { API_BASE_URL } from '../constants/Config';
import BreatheLoader from '../components/BreatheLoader';
import { ATTENDANCE_HISTORY } from '../constants/DummyData';

export default function History() {
  const navigation = useNavigation<any>();
  const [history, setHistory] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useFocusEffect(
    useCallback(() => {
      setLoading(true);
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 3000);

      fetch(`${API_BASE_URL}/history`, { signal: controller.signal })
        .then(res => res.json())
        .then(data => {
          clearTimeout(timeoutId);
          if (Array.isArray(data) && data.length > 0) {
            const mapped = data.map((item: any) => ({
              id: String(item.id),
              date: new Date(item.date).toLocaleDateString('en-US', { month: 'short', day: 'numeric' }),
              className: item.Timetable?.section || 'III IT G',
              subject: item.Timetable?.Subject?.title || 'IT Subject',
              absentCount: item.absentCount || 0,
              smsSent: true
            }));
            setHistory(mapped);
          } else {
            setHistory(ATTENDANCE_HISTORY);
          }
          setLoading(false);
        })
        .catch(() => {
          setHistory(ATTENDANCE_HISTORY);
          setLoading(false);
        });

      return () => clearTimeout(timeoutId);
    }, [])
  );

  const handleClearHistory = () => {
    Alert.alert('Clear History', 'Are you sure you want to delete all attendance logs?', [
      { text: 'Cancel', style: 'cancel' },
      { text: 'Clear', style: 'destructive', onPress: () => {
          setHistory([]);
          fetch(`${API_BASE_URL}/history`, { method: 'DELETE' }).catch(() => {});
      }}
    ]);
  };

  const handleShare = async (item: any) => {
    try {
      await Share.share({
        message: `*ClassTrack Attendance Report*\n\nDate: ${item.date}\nClass: ${item.className}\nSubject: ${item.subject}\nTotal Absentees: ${item.absentCount}\n\nGenerated by ClassTrack`,
      });
    } catch (error: any) {
      console.error(error.message);
    }
  };

  const renderHistoryItem = ({ item, index }: { item: any, index: number }) => (
      <View style={styles.historyCard}>
        <View style={styles.cardHeader}>
          <Text style={styles.date}>{item.date}</Text>
          <View style={[styles.badge, item.absentCount > 0 ? styles.badgeAbsent : styles.badgePerfect]}>
            <Text style={[styles.badgeText, item.absentCount > 0 ? styles.badgeTextAbsent : styles.badgeTextPerfect]}>
              {item.absentCount} Absent
            </Text>
          </View>
        </View>
        <Text style={styles.className}>{item.className}</Text>
        <Text style={styles.subject}>{item.subject}</Text>
        
        
        <View style={styles.cardFooter}>
          {item.smsSent ? (
            <View style={styles.smsSuccessBox}>
              <Icon name="check-circle" size={16} color={Colors.success} />
              <Text style={styles.smsSuccessText}>SMS Sent Successfully</Text>
            </View>
          ) : <View />}

          <TouchableOpacity style={styles.shareBtn} onPress={() => handleShare(item)}>
            <Icon name="share" size={20} color={Colors.primary} />
            <Text style={styles.shareBtnText}>Share</Text>
          </TouchableOpacity>
        </View>
      </View>
  );

  if (loading) {
    return (
      <SafeAreaView style={styles.container}>
        <View style={{ flex: 1, justifyContent: 'center' }}>
          <BreatheLoader message="Loading attendance logs..." />
        </View>
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView style={styles.container}>
      <View style={styles.header}>
        <View style={styles.headerTop}>
          <TouchableOpacity onPress={() => navigation.goBack()} style={styles.backBtn}>
            <Icon name="arrow-back" size={28} color={Colors.text} />
          </TouchableOpacity>
          <Text style={styles.title}>Attendance Logs</Text>
          <TouchableOpacity onPress={handleClearHistory} style={styles.backBtn}>
            <Icon name="delete-outline" size={28} color={Colors.error} />
          </TouchableOpacity>
        </View>
        <Text style={styles.subtitle}>Recent Class Attendance</Text>
      </View>

        <FlatList
          data={history}
          keyExtractor={(item) => item.id}
          renderItem={renderHistoryItem}
          contentContainerStyle={[styles.listContainer, history.length === 0 && styles.listContainerEmpty]}
          showsVerticalScrollIndicator={false}
          ListEmptyComponent={
            <View style={styles.emptyState}>
              <Icon name="history" size={48} color={Colors.textSecondary} style={{ opacity: 0.5, marginBottom: 16 }} />
              <Text style={styles.emptyTitle}>No History Yet</Text>
              <Text style={styles.emptySubtitle}>Submit attendance to see records here.</Text>
            </View>
          }
        />
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
    
  },
  header: {
    paddingHorizontal: 24,
    paddingVertical: 16,
    backgroundColor: '#ffffff',
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  headerTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  backBtn: {
    padding: 4,
    marginLeft: -4,
  },
  title: {
    fontSize: 22,
    fontWeight: '800',
    color: '#0F172A',
  },
  subtitle: {
    fontSize: 14,
    color: '#64748B',
    fontWeight: '600',
    marginTop: 8,
    textAlign: 'center',
  },
  listContainer: {
    padding: 24,
  },
  listContainerEmpty: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyState: {
    alignItems: 'center',
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: Colors.text,
    marginBottom: 8,
  },
  emptySubtitle: {
    fontSize: 14,
    color: Colors.textSecondary,
    fontWeight: '600',
  },
  historyCard: {
    backgroundColor: Colors.surface,
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  date: {
    color: Colors.textSecondary,
    fontSize: 16,
    fontWeight: '700',
  },
  className: {
    fontSize: 20,
    fontWeight: '800',
    color: Colors.text,
    marginBottom: 4,
  },
  subject: {
    fontSize: 14,
    color: Colors.textSecondary,
    fontWeight: '600',
  },
  badge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 10,
  },
  badgePerfect: {
    backgroundColor: '#dcfce7',
  },
  badgeAbsent: {
    backgroundColor: '#fee2e2',
  },
  badgeText: {
    fontSize: 14,
    fontWeight: '700',
  },
  badgeTextPerfect: {
    color: Colors.success,
  },
  badgeTextAbsent: {
    color: Colors.error,
  },
  cardFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
  },
  smsSuccessBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#dcfce7',
    padding: 8,
    borderRadius: 8,
  },
  smsSuccessText: {
    color: Colors.success,
    fontWeight: '700',
    fontSize: 12,
    marginLeft: 6,
  },
  shareBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F0F9FF',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
  },
  shareBtnText: {
    color: Colors.primary,
    fontWeight: '700',
    fontSize: 13,
    marginLeft: 6,
  }
});
